### ISSUE TITLE
Embedded HTML region stops displaying randomly 1.6.4

### ISSUE THREAD

**Issue by mikelwmc** [xibosignage/xibo#162] opened 2015-02-05 12:53 UTC
Hi,
 ver. 1.6.4
Two windows 7 clients html region randomly stops showing external content. I created a custom html rss page that I host externally that both clients show fine but randomly they will stop and the region is blank. To get the content back, I need to close Xibo client and re-launch. Any ideas?

Thanks,
Mike

**Comment by mikelwmc** [comment] 2015-02-08 15:10
If this is caused be internet outage, why wouldn't the html content come back when internet restored?

Thanks

**Comment by dasgarner** [comment] 2015-02-09 17:09
I'm not sure that it would be caused by an internet outage, it sounds more like the regions are failing to load when the layout refreshes.

What durations do you have on those regions?

**Comment by mikelwmc** [comment] 2015-02-09 21:56
Hey Dan, 
Duration is set at 60. The reason I mentioned internet outage is because I thought I read something on the old forum about a similar issue.

Thanks

**Comment by dasgarner** [comment] 2015-02-16 19:16
interestingly I found a problem with the 1.7 player that would have caused this behaviour - but I can't see problems with the old one that would.

I'm a bit stumped i'm afraid (hence the delay)

Can you take a look at the information screen on the player and post a screeshot of it - I am hoping to an inspiring error message to be written there...

**Comment by mikelwmc** [comment] 2015-02-16 22:55
Sorry, information screen? You mean the Xibo Client or client options? The log is filled with
[UI Thread] xmds_GetResource	Unable to get Resource: Unable to get the media resource

**Comment by dasgarner** [comment] 2015-02-17 14:28
I mean when the player is running, press 'i' on the keyboard and a window pops up showing information about the running player.

I wouldn't be surprised that the player was unable to get the resource - as the CMS is unavailable... are there any other bits in there?

**Comment by mikelwmc** [comment] 2015-02-17 22:25
![image](https://cloud.githubusercontent.com/assets/10865497/6238534/d867c0fc-b6c9-11e4-87aa-01fb98847003.png)

**Comment by mikelwmc** [comment] 2015-02-17 22:38
Error is can't resolve web host.
![xiboerror](https://cloud.githubusercontent.com/assets/10865497/6238736/8f2f33f0-b6cb-11e4-9633-d22ce4bd2517.jpg)

**Comment by mikelwmc** [comment] 2015-02-18 15:55
This is happening daily, even multiple time daily after a client relaunch. Does the client only try to resolve the host one time? It doesn't appear that when refresh, it is resolving host. 

Correct me but replacing the host with the IP address doesn't seem like it will correct the issue if the client can't access the CMS it will not retry?

**Comment by dasgarner** [comment] 2015-02-19 10:32
It will retry every collection interval (of course!)

There isn't anything useful logged on that screen unfortunately.

I've looked back at the 1.6.4 code and can't see why the layout timer would stop if the content could not be downloaded. The only thing I can think of is that you have some very long running media on that region which is preventing the layout refresh.

**Comment by mikelwmc** [comment] 2015-02-23 14:33
There is a problem with the refresh. here is a screenshot from this morning. both html regions, weather (right) and feed (left)  will not refresh. There is no error in information (i).
![xiboblank3](https://cloud.githubusercontent.com/assets/10865497/6329505/f940c228-bb3e-11e4-93cb-de6704c8f258.jpg)

**Comment by dasgarner** [comment] 2015-02-24 11:54
What durations do you have on the media on your layout?

**Comment by mikelwmc** [comment] 2015-02-24 18:11
The weather is 120 and the feed is 300. two other are 120 and 300.

**Comment by dasgarner** [comment] 2015-02-26 09:46
OK, so it's not that - I wondered whether the duration was long (i.e. several hours) and that was delaying the refresh.

Interestingly I don't think the webpage media is expiring at all.

Can you try replacing your XiboClient.exe file with this one? https://dl.dropboxusercontent.com/u/353651/XiboClient.exe

Please let me know when you have it so I can take it down from that location.

**Comment by mikelwmc** [comment] 2015-02-26 12:49
Got it, thanks. 
What I've noticed... The machine is scheduled to reboot daily, when the client starts none of the external content will display until the XiboClient is stopped and restarted. I noticed this also after replacing the new client then rebooting the pc, the regions didn't show the content.

**Comment by dasgarner** [comment] 2015-03-01 15:14
So it looks like even with the new player, the regions aren't expiring and reloading?

Can you change your log level to audit, recreate the issue by yanking out the network cable (or something) and then dropbox me the log from the information window?

**Comment by dasgarner** [comment] 2015-03-11 09:34
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!

**Closed by dasgarner** 2015-03-11 09:34 UTC
