### ISSUE TITLE
Using ForecastIO with a proxy server :)

### ISSUE THREAD

**Issue by mattgrimley** [xibosignage/xibo#333] opened 2015-02-25 15:43 UTC
After @dasgarner sorted my twitter stream issues out in #231 i figured it was time to report my similar ForecastIO issue :)

So, pretty much nothing loads in the page except for a little spaceship and a "Powered by Forecast" message.

The log file shows:
```
"2015-02-25 14:45:13","module","","<errormsg>file_get_contents(https://api.forecast.io/forecast/34d46bf4f170f79fa82eb83702b58d70/51.9495,-0.0236?units=auto&amp;lang=en&amp;exclude=flags%2Cminutely%2Chourly): failed to open stream: No connection could be made because the target machine actively refused it.
```

Let me know if you need more of the log! :)

Ta,
Matt

**Comment by MedusaDelft** [comment] 2015-02-25 16:23
@mattgrimley I think this is a duplicate of #298

**Comment by dasgarner** [comment] 2015-02-25 22:05
It is indeed - I didn't ask the right questions in the other issue. Now they we know, lets keep the older one.

**Closed by dasgarner** 2015-02-25 22:05 UTC

**Comment by mattgrimley** [comment] 2015-02-25 22:27
Agreed - my bad - one issue led to another and I forgot to check existing!! Thx :)
