### ISSUE TITLE
duplicate Group showing under Permissions tab

### ISSUE THREAD

**Issue by tali1974** [xibosignage/xibo#146] opened 2015-02-03 22:04 UTC
I have 2 users.
U1 and U2.. I have added them to a UserGroup called Grp1…

The permission list show duplicate of Grp1 as shown in image..

https://www.dropbox.com/s/c2tpauv9udxsitt/img1.jpg?dl=0

T

**Comment by laercionit** [comment] 2015-02-04 00:18
I had the same problem. But on a larger scale. Where did an update, I realized this problem. It seems that the upgrade script generates a record for the most amount of group user. You can find it in tebelas below:

See what the group ID GP1
SELECT * FROM group


Then access the table
SELECT * FROM lkusergroup
order by groupid

see that your group ID appears twice


execute:

delete from lkusergroup where groupid = <ID of your group Duplicate>;


This is not solving the problem at its source, but will remove the duplicate of your screen.

**Comment by laercionit** [comment] 2015-02-04 02:06
Hello my friend,
I did several tests with your problem. My solution will not solve.
The problem is that this permission screen listing the group several times as the number of users in the group. But if performing the procedure that informed, will be removing users in the group.

Unfortunately only the DAN can adjust.
I tried, I'm sorry.

**Comment by xibo-de** [comment] 2015-02-04 06:14
I have the same problem too.
The problem also occurs when you do a clean installation.

**Closed** 2015-02-04 10:09 UTC
