### ISSUE TITLE
Layout Designer: Library is empty with German locale

### ISSUE THREAD

**Issue by zemmediamatiker** [xibosignage/xibo#1092] opened 2017-03-24 08:32 UTC
Xibo 1.8.0 Custom install (Can't try with Docker in our environment)

When editing the schedule in a region and trying to add a media file from the library, the selection window is empty, even if there are files uploaded and accessible from the library itself. Changing the locale back to `en_GB` solves this problem.

![library](https://cloud.githubusercontent.com/assets/11920861/24286261/afcd8620-1074-11e7-93bb-747647132d5a.png)

**Comment by dasgarner** [comment] 2017-03-24 09:36
Same root cause as #1083

**Comment by dasgarner** [comment] 2017-03-24 14:00
Fixed in linked issue.

**Closed by dasgarner** 2017-03-24 14:00 UTC
