### ISSUE TITLE
Layouts with Ampersands (&) in name multiply!

### ISSUE THREAD

**Issue by avrovulcanxh607** [xibosignage/xibo#3126] opened 2023-09-07 14:57 UTC
In Xibo V4.0.0 - ampersands in a layout filename get converted to HTML entities, i.e. `&amp;` - unfortunately this seems to happen recursively, every time the file is saved the first & is also converted to an entity, and so on, forever...

**Comment by dasgarner** [comment] 2023-09-07 15:09
This is the root cause: https://github.com/xibosignage/support/commit/c01fc1dd41ec81aef3df1f775a163407736701d1#diff-1a0bde4bf15777959779aa9b08c9cb73e4c18418561488227369310196f1e44aR212

**Comment by dasgarner** [comment] 2023-09-07 15:28
We're sanitising for input in `edit()` but also again from the database in `query()`. Twig is probably doing it again too.

Interesting!

**Comment by dasgarner** [comment] 2023-09-07 15:42
Haha, as is PHP 7.4 to PHP 8.1 😄 

We will get this looked at and resolved in any case. Thanks.

**Comment by maurofmferrao** [comment] 2023-09-12 13:15
Tested! ✅

**Closed** 2023-09-12 13:22 UTC
Labels: bug, regression
