### ISSUE TITLE
Preview for new text (layout)

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [xibosignage/xibo#182] opened 2015-02-07 09:38 UTC
Would be a nice enhancement when you could add a preview when a new text is edited (with CK Editor).

Because it is very hard to guess what will really be displayed in the region. It may really look awesome in the CK Editor window but look bad or doesn't fit in the region (or is way too small).

For advanced users this seems not to be a problem but for new users it's very hard to handle text regions.

Thanks.

**Comment by dasgarner** [comment] 2015-02-09 17:06
Duplicate of #56

**Closed by dasgarner** 2015-02-09 17:06 UTC
