### ISSUE TITLE
Fonts dont work in Player

### ISSUE THREAD

**Issue by Carlos-Costa** [xibosignage/xibo#318] opened 2015-02-23 14:53 UTC
XIBO 1.7.1 -  WINDOWS CLIENT
Hello, if you upload a Font that you dont have in Windows folder Fonts, the font you uploaded will not work in player client..

**Comment by dasgarner** [comment] 2015-02-24 11:54
Have you followed instructions and clicked "Edit" and Save after uploading?

Does the font work in the CMS?

**Comment by Carlos-Costa** [comment] 2015-02-24 17:56
Yes the font work in CMS.. The problem is in client player windows, if you dont have the font installed in windows the font dont work..

**Comment by dasgarner** [comment] 2015-02-26 09:12
Maybe duplicate of #337

**Closed by dasgarner** 2015-02-26 09:12 UTC
