### ISSUE TITLE
XML/Responsestatusline Connect error 1.71 with client 

### ISSUE THREAD

**Issue by mlowrey** [xibosignage/xibo#308] opened 2015-02-20 17:38 UTC
Dear,

Windows/server171/client170

When trying to connect to CMS ( yes, cms address is correctly spelled, and key Is correct, and installed as admin)
 I get the error:

The server committed a protocol violation. Section=ResponseStatusLine

or / and

xibo response is not well-formed XML

Someone ? I tried on multi computers, all the same.

**Comment by dasgarner** [comment] 2015-02-23 10:54
When you press "Display Admin" do you go to the right page? Is there anything in your CMS logs? Is the CMS in production mode?

**Comment by mlowrey** [comment] 2015-02-23 11:05
HI, thx for your response.

When you press "Display Admin" do you go to the right page?  YES

Is there anything in your CMS logs? NO,doesn’t show any error.

Is the CMS in production mode? YES

**Comment by mlowrey** [comment] 2015-02-23 11:11
In the client log we get this:

LibraryAgent|2/23/2015 12:05:42 PM|Error|LibraryAgent - Run|Exception in Run: Could not find file 'C:\Users\Gebruiker\Documents\Xibo Library\requiredFiles.xml'.
ScheduleManagerThread|2/23/2015 12:05:42 PM|Error|ScheduleManager - LoadNewSchedule|Layout invalid: 0
UI Thread|2/23/2015 12:05:42 PM|Error|MainForm - ChangeToNextLayout|Layout Change to  failed. Exception raised was: Default layout
RequiredFilesAgentThread|2/23/2015 12:05:42 PM|Error|RequiredFilesAgent - Run|Exception in Run: Response is not well-formed XML.
RegisterAgentThread|2/23/2015 12:05:42 PM|Error|RegisterAgent - Run|Exception in Run: Response is not well-formed XML.
ScheduleAgentThread|2/23/2015 12:05:43 PM|Error|ScheduleAgent - Run|Exception in Run: Response is not well-formed XML.

**Comment by dasgarner** [comment] 2015-02-23 11:13
Can you try putting this in your XiboClient.exe.config file?

``` xml
<system.net>
  <settings>
   <servicePointManager expect100Continue="false"/>
  </settings>
 </system.net>
```

**Comment by mlowrey** [comment] 2015-02-23 12:40
Its there already.

Op 23 feb. 2015 om 12:13 heeft Dan Garner <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Can you try putting this in your XiboClient.exe.config file?

<system.net>
  <settings>
   <servicePointManager expect100Continue="false"/>
  </settings>
 </system.net>

-

**Comment by dasgarner** [comment] 2015-02-24 11:50
Can you follow the report fault page? It must be a CMS problem.

**Comment by mlowrey** [comment] 2015-02-24 12:22
-------------------------------------- Environment Checks --------------------------------------
Item 	Status 	Advice
PHP Version 		PHP version 5.3.3 or later required. Detected 5.4.37
File System Permissions 		Write access required for settings.php and install.php
MySQL database (PHP MySql) 		MySQL support must be enabled in PHP.
MySQL database (PDO MySql) 		PDO support with MySQL drivers must be enabled in PHP.
JSON Extension 		PHP JSON extension required to function.
SOAP Extension 		PHP SOAP extension required to function.
GD Extension 		PHP GD extension to function.
Session 		PHP session support to function.
FileInfo 		Requires PHP FileInfo support to function. If you are on Windows you need to enable the php_fileinfo.dll in your php.ini file.
PCRE 		PHP PCRE support to function.
Gettext 		PHP Gettext support to function.
Calendar Extension 		PHP Calendar extension to function.
DOM Extension 		PHP DOM core functionality enabled.
DOM XML Extension 		PHP DOM XML extension to function.
Mcrypt Extension 		PHP Mcrypt extension to function.
Allow PHP to open external URLs 		You must have allow_url_fopen = On in your PHP.ini file for RSS Feeds / Anonymous statistics gathering to function.
DateTimeZone 		This enables us to get a list of time zones supported by the hosting server.
Large File Uploads 		Support for uploading large files is recommended.
-------------------------------------- LOG Dump -------------------------------------- Date,Page,Function,Message -------------------------------------- Display Dump -------------------------------------- DisplayID: 2 Display: PASCAL-PC Default Layout: Logged In: 1 Last Accessed: 1424706007 Interleave: 0 Licensed: 0 -------------------------------------- Settings Dump -------------------------------------- Setting: MEDIA_DEFAULT - Value: private Setting: LAYOUT_DEFAULT - Value: private Setting: defaultUsertype - Value: User Setting: userModule - Value: module_user_general.php Setting: defaultTimezone - Value: Europe/Amsterdam Setting: mail_to - Value: mail@yoursite.com Setting: mail_from - Value: mail@yoursite.com Setting: jpg_length - Value: 10 Setting: ppt_length - Value: 10 Setting: swf_length - Value: 10 Setting: audit - Value: audit Setting: LIBRARY_LOCATION - Value: library/ Setting: HELP_BASE - Value: http://www.xibo.org.uk/manual/en/ Setting: PHONE_HOME - Value: Off Setting: PHONE_HOME_URL - Value: http://www.xibo.org.uk/stats/track.php Setting: PHONE_HOME_DATE - Value: 0 Setting: SERVER_MODE - Value: Production Setting: MAINTENANCE_ENABLED - Value: Off Setting: MAINTENANCE_EMAIL_ALERTS - Value: On Setting: MAINTENANCE_KEY - Value: changeme Setting: MAINTENANCE_LOG_MAXAGE - Value: 2 Setting: MAINTENANCE_STAT_MAXAGE - Value: 2 Setting: MAINTENANCE_ALERT_TOUT - Value: 12 Setting: SHOW_DISPLAY_AS_VNCLINK - Value: 0 Setting: SHOW_DISPLAY_AS_VNC_TGT - Value: _top Setting: MAINTENANCE_ALWAYS_ALERT - Value: Off Setting: SCHEDULE_LOOKAHEAD - Value: On Setting: REQUIRED_FILES_LOOKAHEAD - Value: 172800 Setting: REGION_OPTIONS_COLOURING - Value: Media Colouring Setting: LAYOUT_COPY_MEDIA_CHECKB - Value: Unchecked Setting: MAX_LICENSED_DISPLAYS - Value: 0 Setting: LIBRARY_MEDIA_UPDATEINALL_CHECKB - Value: Unchecked Setting: USER_PASSWORD_POLICY - Value: Setting: USER_PASSWORD_ERROR - Value: Setting: MODULE_CONFIG_LOCKED_CHECKB - Value: Unchecked Setting: LIBRARY_SIZE_LIMIT_KB - Value: 25000 Setting: MONTHLY_XMDS_TRANSFER_LIMIT_KB - Value: 0 Setting: DEFAULT_LANGUAGE - Value: en_GB Setting: TRANSITION_CONFIG_LOCKED_CHECKB - Value: Unchecked Setting: GLOBAL_THEME_NAME - Value: default Setting: DEFAULT_LAT - Value: 51.504 Setting: DEFAULT_LONG - Value: -0.104 Setting: SCHEDULE_WITH_VIEW_PERMISSION - Value: No Setting: SETTING_IMPORT_ENABLED - Value: 1 Setting: SETTING_LIBRARY_TIDY_ENABLED - Value: 1 Setting: SENDFILE_MODE - Value: Off Setting: EMBEDDED_STATUS_WIDGET - Value: Setting: PROXY_HOST - Value: Setting: PROXY_PORT - Value: 0 Setting: PROXY_AUTH - Value: Setting: DATE_FORMAT - Value: Y-m-d H:i Setting: DETECT_LANGUAGE - Value: 1 Setting: DEFAULTS_IMPORTED - Value: 1 Setting: FORCE_HTTPS - Value: 0 Setting: ISSUE_STS - Value: 0 Setting: STS_TTL - Value: 600 Setting: MAINTENANCE_ALERTS_FOR_VIEW_USERS - Value: 0 Setting: CALENDAR_TYPE - Value: Gregorian -------------------------------------- Sessions Dump -------------------------------------- UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36 RemoteAddress: 171.33.129.221 Session Data pagename|s:5:"admin";token_timeout|i:1424778946;message|s:0:"";username|s:10:"xibo_admin";usertype|s:1:"1";token|s:32:"a9fc2f8c8efae4158c69ccbb531358db";layout|a:9:{s:13:"filter_layout";s:0:"";s:13:"filter_userid";i:0;s:14:"filter_retired";i:0;s:20:"filterLayoutStatusId";s:1:"1";s:17:"showDescriptionId";s:1:"2";s:8:"showTags";i:0;s:13:"showThumbnail";i:1;s:11:"filter_tags";s:0:"";s:12:"LayoutFilter";i:0;}gridToken|s:32:"e24be8125a913a97597a455c4dc7f60b";gridToken_timeout|i:1424775236;timeLineView|s:4:"list";userid|s:1:"1";log|a:8:{s:6:"Filter";i:0;s:11:"filter_type";i:0;s:15:"filter_function";s:0:"";s:11:"filter_page";s:0:"";s:13:"filter_fromdt";s:0:"";s:14:"filter_display";i:0;s:14:"filter_seconds";s:3:"120";s:21:"filter_intervalTypeId";s:1:"1";}sessions|a:3:{s:6:"Filter";i:0;s:11:"filter_type";s:0:"";s:13:"filter_fromdt";s:0:"";} ----

**Comment by dasgarner** [comment] 2015-02-24 17:26
After further investigation, this is caused by spaces being output at the beginning of the SOAP response - I am not yet sure why. It might be an environment thing.

**Comment by dasgarner** [comment] 2015-03-11 09:37
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!

**Closed by dasgarner** 2015-03-11 09:37 UTC
