### ISSUE TITLE
DataSet - User can't edit DataSet when used in a Schedule with a DayPart

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1290] opened 2017-09-05 11:16 UTC
Create a dataset, layout using said dataset, create a daypart, then schedule said layout using created daypart.

Create a user and assign him permissions to said dataset.

While our user will be able to see the dataSet on dataSets page, will also be able to see columns/data in the dataSet and enter edit row form, any changes that he attempts to make will end with an error.

With debugging on, it will read as follows:

```
WEB,/dataset/data/16,POST,"lib/Entity/Schedule.php(933): Xibo\Factory\DayPartFactory-&gt;getById(10)
#1 /lib/Entity/Schedule.php(680): Xibo\Entity\Schedule-&gt;calculateDayPartTimes(Object(Jenssegers\Date\Date), Object(Jenssegers\Date\Date))
#2 /lib/Entity/Schedule.php(625): Xibo\Entity\Schedule-&gt;generateMonth(Object(Jenssegers\Date\Date))
#3 /lib/Service/DisplayNotifyService.php(409): Xibo\Entity\Schedule-&gt;getEvents(Object(Jenssegers\Date\Date), Object(Jenssegers\Date\Date))
#4 /lib/Entity/DataSet.php(604): Xibo\Service\DisplayNotifyService-&gt;notifyByDataSetId(16)
#5 /lib/Entity/DataSet.php(480): Xibo\Entity\DataSet-&gt;notify()
#6 /lib/Controller/DataSetData.php(232): Xibo\Entity\DataSet-&gt;save(Array)
#7 [internal function]: Xibo\Controller\DataSetData-&gt;add('16')
#8 /vendor/akrabat/rka-slim-controller/RKA/Slim.php(79): call_user_func_array(Array, Array)
#9 [internal function]: RKA\Slim-&gt;RKA\{closure}('16')
#10 /vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#11 /vendor/slim/slim/Slim/Slim.php(1357): Slim\Route-&gt;dispatch()
#12 /vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim-&gt;call()
#13 /vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash-&gt;call()
#14 /lib/Middleware/Actions.php(142): Slim\Middleware\MethodOverride-&gt;call()
#15 /lib/Middleware/Theme.php(35): Xibo\Middleware\Actions-&gt;call()
#16 /lib/Middleware/WebAuthentication.php(132): Xibo\Middleware\Theme-&gt;call()
#17 /lib/Middleware/CsrfGuard.php(62): Xibo\Middleware\WebAuthentication-&gt;call()
#18 /lib/Middleware/State.php(117): Xibo\Middleware\CsrfGuard-&gt;call()
#19 /lib/Middleware/Storage.php(47): Xibo\Middleware\State-&gt;call()
#20 /lib/Middleware/Xmr.php(36): Xibo\Middleware\Storage-&gt;call()
#21 /vendor/slim/slim/Slim/Slim.php(1302): Xibo\Middleware\Xmr-&gt;call()
#22 /web/index.php(124): Slim\Slim-&gt;run()
```

**Comment by dasgarner** [comment] 2017-10-09 10:15
I can't recreate this issue - it seems like a duplicate of #1214

**Comment by dasgarner** [comment] 2017-10-09 11:37
Fixed: https://github.com/dasgarner/xibo-cms/commit/2d45884d4d7b903161b9535f27617a0a0f5945ee

**Closed by dasgarner** 2017-10-09 11:37 UTC
Labels: bug
