### ISSUE TITLE
Twitter 1.7 module doesn't refresh

### ISSUE THREAD

**Issue by DanTheMan-NL** [xibosignage/xibo#417] opened 2015-03-10 11:30 UTC
Where do I enter the interval time for the new Twitter module for xibo 1.7.1? I have set the time for the twitter region on 3 seconds and I have set the cache period on the Twitter module in the admin CMS to 1 second only nothing is happening on my screen.

Tweets are only refreshing when I re-open the xibo player.

**Comment by ihades** [comment] 2015-03-10 22:23
Same behavior for me. The Preview seems to refresh properly...

**Comment by kb2faf** [comment] 2015-03-11 03:00
I concur...

**Comment by dasgarner** [comment] 2015-03-11 09:19
We are moving discussion and support over to [community.xibo.org.uk](https://community.xibo.org.uk), so we would appreciate you asking on there in future.

I'd imagine your twitter module is the only thing in the Region? If that is the case then it won't refresh until the Layout reloads. If you're running android you could set it to loop the region, if you are running windows you could add the same module again so that they cycle.

**Comment by ihades** [comment] 2015-03-11 17:00
![region-config](https://cloud.githubusercontent.com/assets/4728131/6601859/57bf971c-c818-11e4-969f-c0d05a4ba1bb.PNG)
Sorry for the discussion here, i will respect your movement in future.

Your guess is right, it was the only thing in this region. Adding a secondary Twitter-module won't fix the issue. Even if i add another thing to this region or decrease the cycle-time of the whole Layout it won't reload the Tweets.
![twitter-issue](https://cloud.githubusercontent.com/assets/4728131/6601824/22d5c472-c818-11e4-80c5-eb3bb238f532.png)

**Comment by dasgarner** [comment] 2015-03-11 18:18
After some further investigation since my last comment I believe the problem is tied up into this set of bugs: #404 

Perhaps you can follow the commit of that issue, patch your XiboClient.exe and try again?

**Comment by ihades** [comment] 2015-03-11 18:31
I will try that, but i have no .net experience. Can you recommend a tool chain to build .net (suitable for a Java developer)?

**Comment by dasgarner** [comment] 2015-03-12 13:27
I am suggesting you download the EXE from the link I provided and replace your currently installed EXE with it. That should be all you need to do as I have already fixed and built.

**Comment by DanTheMan-NL** [comment] 2015-03-13 11:57
I have put two of the same twitter apps in the same region with a duration of 30 seconds. Now Twitter does refresh only it takes 5 minutes.

**Comment by dasgarner** [comment] 2015-03-13 13:08
Great - that is expected at the moment as the twitter module doesn't have its own "update interval" setting.

This will be enhanced in #432

**Closed by dasgarner** 2015-03-13 13:08 UTC
