### ISSUE TITLE
Replace in all Layouts overwrites the existing media settings

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#79] opened 2015-01-28 17:25 UTC
On a layout I converted from v.1.6.4 I have a video which I want to play looped, nothing else in the timeline. The Loop tickbox doesn't stay ticked after I save it.

**Comment by dasgarner** [comment] 2015-02-10 14:27
Sorry, but I can't recreate the issue...

Assign a new video
Edit the video and enter a duration and select loop
Save
Edit the video and the loop setting has been saved

**Comment by nagyrobi** [comment] 2015-02-10 15:21
Try on a Layout which was created using Xibo CMS 1.6.4 and contained a region with a video; CMS upgraded to 1.7, and upgraded design from the designer dropdown. I've tested a couple of moments ago with 1.7.1, it's there.
Make sure that in your library you have already uploaded videos and their duration is filled in there.

**Comment by nagyrobi** [comment] 2015-02-10 22:43
I just noticed the same with the Mute tickbox, whick keeps staying ticked, although I want to save it unticked.

By the way on my Android client it doesn't actually mute the video.

**Comment by dasgarner** [comment] 2015-02-12 12:09
I still can't recreate the issue - it works perfectly here. Can I get access to your CMS?

Noted on mute in android - we will look at that.

**Comment by nagyrobi** [comment] 2015-02-13 13:17
Yes. Where should I send you the login credentials?

**Comment by dasgarner** [comment] 2015-02-13 18:23
Could you raise a ticket [here](https://springsignage.freshdesk.com/support/tickets/new) and mark it for my attention?

**Comment by dasgarner** [comment] 2015-02-17 14:15
OK, so the problem is that with "replace in all layouts" ticked, the default initial settings are re-asserted when the media item is replaced.

This seems to be a two-step issue - firstly the layout media item you are editing doesn't need to be replaced (which would solve the immediate issue).

Secondly, only the media item assigned to the layout needs replacing - not the settings. This will be more difficult to solve and might be a 1.8.0-alpha thing.

**Closed** 2015-03-04 14:23 UTC
Labels: bug
