### ISSUE TITLE
Webpage: The player shows only partial rendering of the HTML content

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3424] opened 2024-05-23 14:46 UTC
**Issue:**

A webpage widget on a playlist with a manual position and offset top only shows the webpage partially and does not display the whole page.

**Steps:**

- Add a webpage to a playlist 
- Set the Options as `Manual position`
- Set the `Offset Top` as 150
- Schedule the layout on a player

**Actual Result:**
- On the player, the page is displayed partially and the lower content of the webpage is cutoff

**Expected result**
- Player should display the page content within the boundary of the playlist.

Note that a webpage widget with above settings (i.e., Manual Position and Offset Top) that is not inside a playlist works as expected.

**Comment by dasgarner** [comment] 2024-06-04 20:05
I think this is likely a player issue, so we will remove it from the milestone and investigate further.

**Comment by dasgarner** [comment] 2024-06-12 15:23
OK, this is a CMS issue.

The root cause is that we use the `$(target).height()` to set the height of the iframe and on Android that is a thin letterbox:

![Image](https://github.com/xibosignage/xibo/assets/10400067/eac8ebd7-58d4-42cf-8b48-24ce18bd816f)

Reassigning to current sprint to be worked on.

**Comment by dasgarner** [comment] 2024-06-12 15:51
You can supply a pageHeight to workaround the issue.

**Closed** 2024-06-14 08:35 UTC
Labels: bug
