### ISSUE TITLE
Possible to use old modules for newer version.

### ISSUE THREAD

**Issue by Rating** [xibosignage/xibo#353] opened 2015-02-27 07:28 UTC
Hey.

After the new RSS update it messed up all my Google calendar feeds. So I now trying to use and old ticker module in the new version. It shows in the ui but I cant add it because the "Module file does not contain a class of the correct name". Whats the correct name and how do I edit it?

Are thier any chance that this will work?.

**Comment by dasgarner** [comment] 2015-02-27 09:39
There is no chance it will work, you will need to revert to the prior version entirely.

**Comment by Rating** [comment] 2015-02-27 09:57
Ok. Are thier any easy way for me to edit the new ticker so that it sorts like the old one did? The new update exclude Google Calender rss. I cant even change the "Take items from the Start or End of the feed" in settings.

This issue may stop me from using Xibo. I really like the plattform and its perfect for the School I work at.

**Comment by dasgarner** [comment] 2015-02-27 10:42
Duplicate of #345

**Closed by dasgarner** 2015-02-27 10:42 UTC
