### ISSUE TITLE
Improve the experience when designing layouts for tiny screen sizes

### ISSUE THREAD

**Issue by knitehawk** [xibosignage/xibo#59] opened 2015-01-25 22:37 UTC
it would be preferable to not only be able to set the display size but also assign a custom resolution instead of adding it as a background in layout. reason is
for instance i have a 64x256 sign. lots of things will not display properly in a display that small, but if i up the resolution as a background it will render just fine and give me a large enough area to work with.
for 64x256 i use 192x768 and it looks great, also is large enough to put forecast ip images on it.

this should be invisible to the user level access

**Comment by dasgarner** [comment] 2015-01-26 09:33
Sorry - you have totally baffled me :-)

Wouldn't you just have a custom resolution which you assigned to your Layout?

**Comment by knitehawk** [comment] 2015-01-26 15:20
sure if it always came up every time i click add layout as a default.
if you make a sign at 64x256 you will see what im talking about.
the layout area is just to small to edit in the layout design area.
Yes i know you can click enlarge in the design region page, but you have to click it about 15 times and it takes a while. also, if you add text or forecast io 1 is the smallest size for fio, and the images don't fully make it onto the screen all the time. the fix is to add a resolution thats larger but maintains aspect .
from the "user" point of view, they don't need to ever see that. why would they ever need to change the resolution?
so you put a default resolution in the display settings for that display and it will come up without having to attach it every time you make a layout.
if you don't then you will constantly get calls asking "Why is my region so small now? it was big that one time when you trained me, and now i don't remember how to get it big again."

does that make sense?

**Comment by dasgarner** [comment] 2015-01-26 20:52
I do now understand what you are battling against - there was a problem with the scale calculation that rendered your layout tiny, instead of small. I have linked a commit that you could drop into your installation to see how it looks when it works as it should.

I **think** 192x768 results in the same actual designer window (after the fix) as the original 64x256 - it ought to do so as you have the same aspect ratio.

**Comment by knitehawk** [comment] 2015-01-26 23:32
Hmm no, they both look different.
the larger resolution positions everything much better
the smaller resolution everything is to large.
see template and css below.

also, from a user point of view it's ease of use (you kinda have to think like your grand mother)
"what does this mean? resolution? whats that?"
vs
"i clicked my sign is the box and it worked"
i can almost guaranty 99.5% of users have no idea how to code html php and probably have never heard of them. much less laying anything out. or they think 1080p is an aspect ratio.
it would be better to walk them through it. 
if you make it a setting in display config then
click add layout->
what display? <drop down box populated with the displays they are assigned.>-->
 layout design

it's much harder to screw up.

or a drop down box in the layout designer that only renders the display when you select a display(again only populated with the displays assigned to them and again with resolution assigned behind there back in display settings.)



this is my template
<div align="center" class="icon std-sprite-[icon]">
</div>
<div align="center" class="container">
    <div align="center"class="desc">[summary]</div>
    <div align="center"class="temperature">Temp [temperatureFloor]<i class="wi wi-degrees"></i></div>
<div align="center" class="humidity">Humidity [humidity]</div>


this is my css
body {
    font-family:Arial;
    margin:0;
    padding-top: 5px;
}

.icon {
    float: left;
    background: url([[ICONS]]) no-repeat top left;
}

.temperature {
    font-size: 46px;
}

.humidity {
    font-size: 46px;
}
.desc {
    padding-top: 20px;
    font-size: 34px;
}


.std-sprite-clear-day{ background-position: 0 0; width: 128px; height: 128px; } 
.std-sprite-clear-night{ background-position: 0 -178px; width: 128px; height: 128px; } 
.std-sprite-cloudy{ background-position: 0 -356px; width: 128px; height: 128px; } 
.std-sprite-lightning{ background-position: 0 -534px; width: 128px; height: 128px; } 
.std-sprite-partly-cloudy-day{ background-position: 0 -712px; width: 128px; height: 128px; } 
.std-sprite-partly-cloudy-night{ background-position: 0 -890px; width: 128px; height: 128px; } 
.std-sprite-rain{ background-position: 0 -1068px; width: 128px; height: 128px; } 
.std-sprite-sleet{ background-position: 0 -1246px; width: 128px; height: 128px; } 
.std-sprite-snow-night{ background-position: 0 -1424px; width: 128px; height: 128px; } 
.std-sprite-snow{ background-position: 0 -1602px; width: 128px; height: 128px; } 
.std-sprite-wind{ background-position: 0 -1780px; width: 128px; height: 128px; }

**Comment by knitehawk** [comment] 2015-01-27 03:38
ok, i replaced the file you suggested. somewhere along the way i crashed the sql, had to remake and reinstall xibo.
did some playing around and this one works
$designerScale = ($version == 1) ? 1 : min($resolution['width'] / $resolution['intended_width'], $resolution['height'] / $resolution['height']);
but only on the larger resolution. small resolution does not scale. probably because the fonts are not going down that far.
best to lock resolution of choice into sign settings. and let the renderer work. setting resolution to 3x h and w looks great.

**Comment by dasgarner** [comment] 2015-01-27 09:01
The problem is that we had a large number of requests to do exactly the opposite of what you are suggesting - i.e. allow the selection of a resolution not an aspect ratio... and unfortunately it cannot work both ways at the same time :)

I'm sure you saw in 1.6 and before that all you did was select an aspect ratio and you were done, no adjustments to the resolution necessary.

The display could be told to report it's resolution back to the CMS, and we could use that to do something - but I don't see we can drop the resolution selector if that is what people want. It is also important that Layouts are designed at the resolution they are intended for so that we do as little scaling as possible.

I'm still not entirely sure I see the problem - i've replaced my file and I get this:

![image](https://cloud.githubusercontent.com/assets/10400067/5915921/2188f3a0-a603-11e4-8c3c-e7061f053ad1.png)

**Comment by dasgarner** [comment] 2015-01-27 09:10
It seems that the default sizing is just way to large for such a tiny screen area - even the sprites includes are larger than your screen width.

I do now see why designing at a higher resolution will have an effect, but I am still not sure what to do about it.

**Comment by knitehawk** [comment] 2015-01-27 14:17
Ahh i see the confusion. 
i thinbk i was not clear in the request.
i don't want to change what you've done already to much.
admin should be able to see custom resolutions and ratio. just the way it is.
customer/user should only have to select their display. and the best rosolution (pre picked by the admin, if that display need custom settings.)
the ability to change resolutions and aspect ratios is undisturbed. just shielding the user a bit.
if possible have a display selection dialogue when you select add region to ask the customer which display they want to design for.
then it loads in the settings and sizes the design screen apropriatly.

might just be a pulldown in the region design screen with all settings for the display loaded in.
real resolution, or aspect ratio, plus design zoom setting. all in one.
that way users with multiple resolution displays don't have to keep track of the settings for each display.
if they WANT to go in and change it in the background.. thats fine. but then if they screw it up, they did it.


sorry for not being clear. 
does that make more sense?

**Comment by dasgarner** [comment] 2015-01-28 09:23
If we had permissions on Resolutions, couldn't we achieve the same thing by creating a template called "User should use this"?

**Comment by knitehawk** [comment] 2015-01-30 00:40
Hmm, thats an idea. i will play around with that

**Closed** 2015-08-19 15:57 UTC
Labels: requires blueprint
