### ISSUE TITLE
Screenshot feature cannot capture areas rendered by the GPU

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#126] opened 2015-02-02 15:25 UTC
I'm using v1.7, CMS and Android clients. I see in the web interface that there's a "Request Screen Shot" option on the display's dropdown menu. Clicking on it says "Are you sure you want to request a screen shot? The next time the client connects to the CMS the screen shot will be sent." And nothing happens. Tried to trigger a connect manually from the Android client's menu, but still nothing.
Also there's no visible place in the CMS web interface to actually display the screenshot, thus I really can't tell where's the problem.

**Comment by dasgarner** [comment] 2015-02-02 17:31
If you open the display filter you can select whether you want to view screen shots or not.

Screenshots will only be sent once the player connects on its regular collection interval - you can also specify another interval in a Display Profile.

**Comment by nagyrobi** [comment] 2015-02-02 17:43
D'oh! I would never though that I should search for Screenshots in a filter window.

But - still - real screenshots are not taken, all I have is black screens in the screenshot. I've even set the Screen shot interval to 1 minute but I still don't get them.

**Comment by dasgarner** [comment] 2015-02-02 18:16
I suspect that it is taking a screenshot, but that the video doesn't appear - and as it is full screen, you just get black.

Can you try with some other non-video content and see if your screenshot comes through?

**Comment by nagyrobi** [comment] 2015-02-02 18:28
I've got a layout with photos and a clock, and it doesn't work either.

**Comment by sourjya** [comment] 2017-10-12 08:37
This appears to be still an open issue? I'm getting black screenshots as well. Anyone else experiencing the same?

**Comment by alexharrington** [comment] 2017-10-12 08:38
The issue isn't closed, so yes it is still an issue. In most cases though, turning off Surface View will allow you to get a screenshot (assuming your device supports it)

**Comment by IkKan** [comment] 2019-03-19 11:00
Is there any progress about this issue? It would be nice to solve it...

**Comment by dasgarner** [comment] 2019-03-19 11:10
In some cases you can use a Texture VideoView (an option in settings), in some cases we've implemented a device specific workaround (i.e Philips devices) and in some cases the device provides an external screenshot intent which can be configured in display settings.

Unfortunately it is not possible to fully resolve this issue on all devices.

**Comment by dasgarner** [comment] 2020-02-03 08:27
Closing during house keeping. There are various workarounds for specific devices, but no general all-purpose solution.

**Closed by dasgarner** 2020-02-03 08:27 UTC
Labels: bug
