### ISSUE TITLE
Error set Users Retired

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#443] opened 2015-03-19 02:18 UTC
When we mark a user as he retired some user list, no longer can view or reactivate the user. Only through the database you can undo the action.

![image](https://cloud.githubusercontent.com/assets/325662/6723320/01bec5f6-cdc5-11e4-8617-14b944e751a9.png)

**Comment by dasgarner** [comment] 2015-03-19 09:09
You just show retired users in the filter?

**Comment by laercionit** [comment] 2015-03-19 13:54
Dan, I found relevant break in two different issues.

A related display of the grid and filter and the other with respect to define a user to retired

https://github.com/xibosignage/xibo/issues/442
https://github.com/xibosignage/xibo/issues/443

**Comment by dasgarner** [comment] 2015-03-19 17:19
OK, will mark this as duplicate of #442

**Closed by dasgarner** 2015-03-19 17:19 UTC
