### ISSUE TITLE
1.7.1 CMS Assign Library Images to Layout Timeline Fails

### ISSUE THREAD

**Issue by kevinrsalisbury** [xibosignage/xibo#209] opened 2015-02-10 12:49 UTC
Background:
- Using 1.7.1
- Using new 16:10 Layout
- Library contains properly sized and timed (duration) images in a supported format (png)
- Layout in question displays ForecastIO and text in proper timeline, but will not assign media (images) from library, or from a direct upload to the layout

I am a new user of Xibo so it's quite likely I am doing something extremely silly, however I have RTFM and I am still having trouble. I have attempted to assign Library images to a layout timeline/playlist by using several Firefox versions on Linux and Windows, as well as Chrome on Windows. I am able to see the image records in the library, and I am able to click the + to move the images up to the assignment bar, however when I select them and attempt to assign them to the layout using the assign button in the lower right of the window. Nothing happens on Firefox and on Chrome the blue highlight around the assign button stays lit. There appear to be no errors in the error log. As I have noted above, I have uploaded the images in questions twice to the library and once to the layout - I am out of ideas.

**Comment by dasgarner** [comment] 2015-02-10 12:51
Probably a duplicate of #186, which has been fixed and the release files patched yesterday. Can you try re-downloading and copying over your existing install.

**Closed by dasgarner** 2015-02-10 12:51 UTC

**Comment by kevinrsalisbury** [comment] 2015-02-10 14:45
#186 Solution solved the issue. Thanks.
